### ISSUE TITLE
Add more export formats

### ISSUE THREAD

**Issue by amir-zeldes** [amir-zeldes/rstWeb#79]
Use .dis converter with/without binarization, maybe also RSD export

**Comment by mohamadi-sara20** [comment]
Hi!
Is there any library you'd recommend be used for this task? Or do you recommend writing the conversion code from scratch? 
I have used this code for the conversion rs3  files to lisp:
https://github.com/arne-cl/discoursegraphs
But some of my files could not be converted. I didn't finally realize why; I am a newbie to rst annotation though, so that could be the reason. I will try to debug and find the reason asap. 

Anyways, if the above code could be used for conversion, I can add it to rstweb. Would that be acceptable?

**Comment by amir-zeldes** [comment]
Mm, actually I have some standalone code for converting rs3 to dis (binarized or non-binarized lisp). You can find it here:

https://github.com/amir-zeldes/gum/blob/dev/_build/utils/rst2dis.py

I think it should be pretty easy to integrate into rstweb, since it just expects the .rs3 XML string the way that rstWeb produces it. It's probably easier than using discoursegraphs because it doesn't have any dependencies.

**Comment by amir-zeldes** [comment]
Implemented by @rknaebel in #90
