### ISSUE TITLE
rstWeb display issue when multinuc and nuc-sat share the same parent id

### ISSUE THREAD

**Issue by logan-siyao-peng** [amir-zeldes/rstWeb#87]
Taking wsj_0614 as an example, the CONTRAST relation between EDU 1 and 2, as well as the ELABORATION-ADDITIONAL of EDUs 3-9 are shown at one level in rstWeb.
The wsj_0614.rs3 file shows the following:

	<body>
		<segment id="1" parent="5001" relname="Contrast">...</segment>
		<segment id="2" parent="5001" relname="Contrast"> ...</segment>
		...
		<group id="5002" type="span" parent="5001" relname="elaboration-additional"/>

![image](https://user-images.githubusercontent.com/10673571/103555493-5711d680-4eeb-11eb-985d-3747d99aa328.png)

**Comment by amir-zeldes** [comment]
OK, this is fixed in dev now. I'm planning some more additions so I'll hold off on a new release for a bit still. 

Note that the solution is just a heuristic, and it's still possible to get errors, since the RS3 format is actually ambiguous in this situation:
  * The same relation label has been used for both multinuclear and satellite-nuclear relations
  * The node above 1-2 is declared as a multinuc
  * The relations from 1 and 2 must be multinuclea, but 3-9 is ambiguous (the group node does not show which version is being used, S-N or N-N)

In the fix, we check whether the multinuc parent actually has 2+ children of that type - in this case, it has 2xContrast and only 1xelaboration-additional, so it makes sense to guess that the elab-additional is S-N, and contrast is the proper N-N child. But the following situation would still be ambiguous:

  * there are multiple rels which can be both NN and SN
  * the same multinuc node has 4+ children of which 2 are ambig rel1 and 2 are ambig rel2

In this case we can't automatically guess what is correct based on the RS3 format...
